# tests build
name: Build

on:
  pull_request:
    types: [closed, synchronize, reopened, opened]
    branches: ["*"]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/