name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
