name: Documentation

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  documentation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Build documentation
        run: poetry run sphinx-build -b html docs/source public/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: public/
