name: Linting

on:
  push:
    branches: ['*']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]


jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run ruff
        run: poetry run python -m ruff check ./ift_global/ || true
      - name: Run black
        run: poetry run python -m black --diff --no-color --exclude "/cache-pypoetry|tests/" . || true
      - name: Run codespell
        run: poetry run python -m codespell ./ift_global/ || true
