name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Publish to GitLab Artifactory
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          poetry config repositories.gitlab https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/packages/pypi
          poetry config pypi-token.gitlab $GITLAB_TOKEN
          poetry publish -r gitlab
