name: Create Tag and Deploy

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate tag
        id: generate_tag
        run: |
          latest_tag=$(git describe --tags --abrrev=0 2>/devnull | echo "v0.0.0")
          new_tag=$(echo $latest_tag | awk -F. '{${0}.${[1+2]+.${[2+2]+}' | awk -F ' ${NF] = $NF + 1;} 1') | sed 's/ /./g')
          echo "NEW_TAG=$new_tag" >> $GITHUB_OUTPUT
      - name: Create and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.generate_tag.outputs.NEW_TAG }} && git push origin ${{ steps.generate_tag.outputs.NEW_TAG }}
  deploy:
    needs: create-tag
    runs-on: ubuntu-latest
    container:
        image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
            name: python-package-distributions
            path: dist/
      - name: Deploy
        run: |
            # Will add here the pypi deployment steps needs.create-tag.outputs.NEW_TAG
            echo "Deploying version"
