name: Test

on:
  push:
    branches: ['*']
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run python -m pytest ./ift_global/tests --cov-report=xml --cov-report=term --cov-branch --junit-xml=report.xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: report.xml

  publishcov:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: report.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true