name: Vulnerability Scan

on:
  push:
    branches: ['*']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run Bandit
        run: poetry run python -m bandit -c pyproject.toml -r ift_global -f xml -o vulnerability_test.xml || true
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: vulnerability_test.xml

  publishcov:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: vulnerability-scan
    steps:
      - uses: actions/checkout@v3
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: vulnerability-report
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: vulnerability_test.xml
          flags: vulnerability_test
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true