name: Vulnerability Scan

on:
  push:
    branches: ['*']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run Bandit
        run: poetry run python -m bandit -c pyproject.toml -r ift_global -f xml -o vulnerability_test.xml || true
