name: Vulnerability Scan

on:
  workflow_call:

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run Bandit
        run: poetry run python -m bandit -c pyproject.toml -r ift_global -f xml -o vulnerability_test.xml || true
